version: "3.3"

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - APP_DAPP_ADDRESS=3P8Fvy1yDwNHvVrabe4ek5b9dAwxFjDKV7R
      - APP_DAPP_SEED=
      - APP_WEBHOOK_HOST=ventuary-dao-webhook
      - PORT=80
    volumes:
      - /srv/ventuary-dao/data:/data
    container_name: ventuary-dao-app
    networks:
      - app
      - ventuary-dao
    labels:
      traefik.port: 80
      traefik.domain: ventuary-dao.dev.kozhindev.com
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.SSLHost: ventuary-dao.dev.kozhindev.com
      traefik.frontend.headers.SSLForceHost: true
      traefik.frontend.rule: "Host:ventuary-dao.dev.kozhindev.com"
    depends_on:
      - redis
      - webhook

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - /srv/redis/data:/data
    container_name: ventuary-dao-redis
    networks:
      - ventuary-dao
    labels:
      traefik.enable: false

  webhook:
    restart: unless-stopped
    image: staticfloat/docker-webhook
    hostname: ventuary-dao-webhook
    volumes:
      - ./:/src
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WEBHOOK_SECRET=m4HsAp2o9DcLK4B042glyJEiCxVjcWaj
      - WEBHOOK_HOOKS_DIR=/src/hooks
      - WEBHOOK_BRANCH_LIST=vkozhin
    expose:
      - 8000
    labels:
      traefik.port: 8000
      traefik.domain: ventuary-dao.dev.kozhindev.com
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.SSLHost: ventuary-dao.dev.kozhindev.com
      traefik.frontend.headers.SSLForceHost: true
      traefik.frontend.rule: "Host:ventuary-dao.dev.kozhindev.com;PathPrefixStrip:/_webhook"
    networks:
      - app
      - ventuary-dao

networks:
  ventuary-dao:
  app:
    external:
      name: app
